### ISSUE TITLE
[enhancement] Add SwiftmailerBundle configuration bridge

### ISSUE THREAD

**Issue by vincentchalamon** [AccordGroup/MandrillSwiftMailerBundle#23]
As this bundle is dependent of Swiftmailer, it should be interesting to bridge its configuration through `swiftmailer` (in a bundle use), like:
```yml
swiftmailer:
    # ...
    mandrill:
        transport: accord_mandrill
        api_key: %mandrill_api_key%
        async: %mandrill_async%
        subaccount: %mandrill_async%
```
(Also rename transport to `mandrill`) @Rattler3
